# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chinese_pinyin}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2010-03-10}
  s.description = %q{translate chinese hanzi to pinyin.}
  s.email = %q{flyerhzm@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "data/Mandarin.dat",
    "lib/chinese_pinyin.rb",
    "test/test_helper.rb",
    "test/chinese_pinyin_test.rb"
  ]
  s.homepage = %q{http://github.com/flyerhzm/chinese_pinyin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{translate chinese hanzi to pinyin.}
  s.test_files = [
    "test/test_helper.rb",
     "test/chinese_pinyin_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

