# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chinese_pinyin"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = "2013-03-01"
  s.description = "translate chinese hanzi to pinyin."
  s.email = "flyerhzm@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "chinese_pinyin.gemspec",
    "data/Mandarin.dat",
    "lib/chinese_pinyin.rb",
    "test/Words.dat",
    "test/chinese_pinyin_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/flyerhzm/chinese_pinyin"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0"
  s.summary = "translate chinese hanzi to pinyin."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chinese_pinyin>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<chinese_pinyin>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<chinese_pinyin>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

